serviceName: sorted-docs
namespace: docs

deployment:
  replicaCount: 2
  maxSurge: 1
  maxUnavailable: 0

resources:
  requests:
    memory: "64Mi"
    cpu: 50m
  limits:
    memory: "128Mi"
    cpu: 150m

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/issuer: "letsencrypt"
  hosts:
    - host: docs.sorted.com
      paths:
        - /
    - host: docs-live.sorted.com
      paths:
        - /
  tls:
    - secretName: docs-sorted-com-cert
      hosts:
        - docs.sorted.com
    - secretName: docs-live-sorted-com-cert
      hosts:
        - docs-live.sorted.com
