serviceName: sorted-docs-preview
namespace: docs

deployment:
  replicaCount: 1
  maxSurge: 1
  maxUnavailable: 0

resources:
  requests:
    memory: "64Mi"
    cpu: 50m
  limits:
    memory: "128Mi"
    cpu: 150m

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/issuer: "letsencrypt"
  hosts:
    - host: docs-preview.sorted.com
      paths:
        - /
  tls:
    - secretName: docs-preview-sorted-com-cert
      hosts:
        - docs-preview.sorted.com
