openapi: 3.0.1
info:
  title: Sorted Labels API
  version:
    $ref: ./shared.yaml#/version
  description:
    $ref: ./intro-labels.yaml#/description
  contact:
    $ref: ./shared.yaml#/contact
servers:
  $ref: ./shared.yaml#/servers
paths:
  "/labels/{shipmentReference}/{contentType}/{dpi}":
    get:
      tags:
        - Labels
      summary: Get Labels
      parameters:
        - name: shipmentReference
          in: path
          description: The reference of the `shipment` to retrieve the labels for
          required: true
          schema:
            type: string
            description: The reference of the `shipment` to retrieve the labels for
        - name: contentType
          in: path
          description: The format of document to return
          required: true
          schema:
            $ref: "#/components/schemas/Sorted.Shipments.DataContracts.Enums.ContentType"
        - name: dpi
          in: path
          description: The dpi of the document to return. Has a default value of `203`
          required: true
          schema:
            type: integer
            description: The dpi of the document to return. Has a default value of `203`
            format: int32
        - name: x-api-version
          in: header
          description: The version of the API to use.  Version `1.1` should be supplied with all requests.
          required: true
          style: simple
          schema:
            type: string
            description: The version of the API to use. Version `1.1` should be supplied with all requests.
      responses:
        "200":
          description: The request was successful. The response will include the label
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Sorted.Shipments.DataContracts.Document"
        "400":
          description: There is a validation error in your request
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Sorted.Shipments.DataContracts.ApiError"
        "403":
          description: You do not have permission to retrieve labels for a `shipment`
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Sorted.Shipments.DataContracts.ApiError"
        "404":
          description: The `shipment` could not be found
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Sorted.Shipments.DataContracts.ApiError"
  ? "/labels/{shipmentReference}/contents/{contentsReference}/{contentType}/{dpi}"
  : get:
      tags:
        - Labels
      summary: Get Contents Label
      parameters:
        - name: shipmentReference
          in: path
          description: The reference of the `shipment` to retrieve the label for
          required: true
          schema:
            type: string
            description: The reference of the `shipment` to retrieve the label for
            example: sp_00880362751987348104831746179081
        - name: contentsReference
          in: path
          description: The reference of the `shipment_contents` to retrieve the label for
          required: true
          schema:
            type: string
            description: The reference of the `shipment_contents` to retrieve the label for
            example: sc_00880363564234345002132734890212
        - name: contentType
          in: path
          description: The format of document to return
          required: true
          schema:
            $ref: "#/components/schemas/Sorted.Shipments.DataContracts.Enums.ContentType"
        - name: dpi
          in: path
          description: The dpi of the document to return
          required: true
          schema:
            type: integer
            description: The dpi of the document to return
            format: int32
            example: 203
        - name: x-api-version
          in: header
          description: The version of the API to use.  Version `1.1` should be supplied with all requests.
          required: true
          style: simple
          schema:
            type: string
            description: The version of the API to use. Version `1.1` should be supplied with all requests.
      responses:
        "200":
          description: The request was successful. The response will include the label
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Sorted.Shipments.DataContracts.Document"
        "400":
          description: There is a validation error in your request
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Sorted.Shipments.DataContracts.ApiError"
        "403":
          description: You do not have permission to retrieve labels for a `shipment`
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Sorted.Shipments.DataContracts.ApiError"
        "404":
          description: The `shipment` could not be found
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Sorted.Shipments.DataContracts.ApiError"
components:
  schemas:
    Sorted.Shipments.DataContracts.Link:
      required:
        - href
        - rel
        - type
      type: object
      properties:
        href:
          type: string
          description: The URL of the resource
        rel:
          type: string
          description: "A string representing the relationship of the linked resource to the current resource. For example, a\r\n`link` to a `shipment` will have a value of `shipment`. Links to the current object will have a `rel` of\r\n`self`."
        reference:
          type: string
          description: "When a `link` is a pointer to a resource with a unique reference, this property will contain the reference.\r\nFor instance, a `link` for a `shipment` will contain the `shipment's` reference in this field."
          nullable: true
        type:
          type: string
          description: The type of resource that this `link` points to.
      additionalProperties: false
      description: "A `link` object that provides a pointer to a resource. Links are provided, for example, following the\r\ncreation of a new resource (such as a `shipment`). The `link` will provide access to the created resource."
    Sorted.Shipments.DataContracts.ApiErrorMessage:
      required:
        - code
        - message
      type: object
      properties:
        property:
          type: string
          description: "The path to the affected property, if applicable.\r\n            \r\n> Note: this will be expressed in JSON Path format e.g. `$.addresses[0].address_type` indicates an issue\r\nwith the property `address_type` for the first provided address."
          nullable: true
        message:
          type: string
          description: A plain-text summary of the error.
        code:
          type: string
          description: A pre-defined code for this error.
      additionalProperties: false
      description: The `api_error_message` object provides further information relating to errors.
    Sorted.Shipments.DataContracts.ApiError:
      required:
        - code
        - correlation_id
        - message
        - reference
      type: object
      properties:
        reference:
          maxLength: 35
          minLength: 35
          type: string
          description: A unique reference for this error
        correlation_id:
          type: string
          description: "The correlation id for this error. Customers can use this property when reporting issues to Sorted and this\r\nwill aid with problem discovery and resolution."
        code:
          type: string
          description: A pre-defined `code` for this error.
        message:
          type: string
          description: A plain-text summary of the error.
        details:
          minItems: 0
          type: array
          items:
            $ref: "#/components/schemas/Sorted.Shipments.DataContracts.ApiErrorMessage"
          description: "A collection of `api_error_messages` which provide further details of the error(s), if applicable."
          nullable: true
        _links:
          minItems: 0
          type: array
          items:
            $ref: "#/components/schemas/Sorted.Shipments.DataContracts.Link"
          description: Provides links to further relevant information such as links to documentation.
          nullable: true
      additionalProperties: false
      description: "This object is returned by Sorted whenever an error occurs during a request. Errors can have many causes, such\r\nas badly-formed requests, incorrect permissions, or unforeseen issues during request processing."
    Sorted.Shipments.DataContracts.Enums.ContentType:
      enum:
        - pdf
        - zpl
      type: string
      description: The supported document content types
    Sorted.Shipments.DataContracts.Enums.DocumentType:
      enum:
        - other
        - label
        - cn22
        - cn23
        - commercial_invoice
        - collection_note
        - hazard_label
      type: string
      description: Represents the document types recognised by Sorted
    Sorted.Shipments.DataContracts.Document:
      required:
        - content_type
        - document_type
        - dpi
        - file
      type: object
      properties:
        file:
          type: string
          description: The contents of the file encoded in base64
        content_type:
          type: string
          description: "The format of the document (`application/pdf`, `text/plain`)"
        document_type:
          $ref: "#/components/schemas/Sorted.Shipments.DataContracts.Enums.DocumentType"
        dpi:
          type: integer
          description: The DPI of the document (e.g. `203`)
          format: int32
      additionalProperties: false
      description: This object represents a single document.
  securitySchemes:
    API Key:
      type: apiKey
      name: x-api-key
      in: header
security:
  - API Key: []
